In [91]:
# Opakování Hlasy

import pandas as pd

In [92]:
data=pd.read_csv("votes.csv")
data.head(5)

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,659170,1182850,20210113,NaN,DEMOCRAT
1,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,504070,1182850,20210113,NaN,REPUBLICAN
2,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"MADDOX, LESTER",AMERICAN INDEPENDENT PARTY,False,9198,1182850,20210113,NaN,OTHER
3,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"BUBAR, BENJAMIN """"BEN""""",PROHIBITION,False,6669,1182850,20210113,NaN,OTHER
4,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"HALL, GUS",COMMUNIST PARTY USE,False,1954,1182850,20210113,NaN,OTHER

V souboru votes.csv jsou data o výsledcích voleb ve Spojených státech amerických v období 1976 až 2020. Důležité pro nás budou následující sloupce:

- year - rok,
- state - stát,
- party_detailed - strana, za kterou kandidát(ka) kandidoval(a),
- candidatevotes - počet hlasů pro kandidáta (kandidátku) v daném roce a státě.
-
Vytvoř tabulky, které budou zobrazovat následující data.

Celkový počet odevzdaných hlasů v jednotlivých letech.
Celkový počet odevzdaných hlasů pro kandidáty a kandidátky jednotlivých stran pro volby v roce 2020.
Celkový počet odevzdaných hlasů pro kandidáty dvou hlavních stran (DEMOCRAT a REPUBLICAN) pro všechny volby od roku 1980.
Celkový počet odevzdaných hlasů pro stát MONTANA pro všechny roky.

In [93]:
data = data[["year", "state", "party_detailed", "candidatevotes"]] 
data.head()

   year    state              party_detailed  candidatevotes
0  1976  ALABAMA                    DEMOCRAT          659170
1  1976  ALABAMA                  REPUBLICAN          504070
2  1976  ALABAMA  AMERICAN INDEPENDENT PARTY            9198
3  1976  ALABAMA                 PROHIBITION            6669
4  1976  ALABAMA         COMMUNIST PARTY USE            1954

In [94]:
data.party_detailed.unique()

<StringArray>
[                  'DEMOCRAT',                 'REPUBLICAN',
 'AMERICAN INDEPENDENT PARTY',                'PROHIBITION',
        'COMMUNIST PARTY USE',                'LIBERTARIAN',
                          nan,                'INDEPENDENT',
          'SOCIALIST WORKERS',                   'AMERICAN',
 ...
         'THE BIRTHDAY PARTY',            'BREAD AND ROSES',
         'US TAXPAYERS PARTY',        'GRUMPY OLD PATRIOTS',
        'AMERICAN SOLIDARITY',               'CONSTITUTION',
              'LIBERTY UNION',               'BOILING FROG',
                 'BULL MOOSE',            'APPROVAL VOTING']
Length: 173, dtype: str

In [95]:
data.groupby("year")
data.groupby("year")["candidatevotes"]
data.groupby("year")["candidatevotes"].sum()
data.groupby("year")["candidatevotes"].sum().sort_values(ascending=False)

year
2020    158528503
2016    136787187
2008    131419253
2012    129139997
2004    122349450
2000    105593982
1992    104599780
1996     96389818
1984     92654861
1988     91586825
1980     86496851
1976     81601344
Name: candidatevotes, dtype: int64

In [96]:
data.groupby("year").agg(total_votes=("candidatevotes", "sum"))

      total_votes
year
1976     81601344
1980     86496851
1984     92654861
1988     91586825
1992    104599780
1996     96389818
2000    105593982
2004    122349450
2008    131419253
2012    129139997
2016    136787187
2020    158528503

In [97]:
# data["year"] ==2020

#data [data["year"] ==2020]
(data[data["year"] == 2020]

    .groupby("party_detailed")

    .agg(total_votes=("candidatevotes", "sum"),

         min_votes=("candidatevotes", "min"))

    .sort_values(by="total_votes", ascending=False)

)

                                          total_votes  min_votes
party_detailed
DEMOCRAT                                     81268908      73491
REPUBLICAN                                   74216146      18586
LIBERTARIAN                                   1797355       2036
GREEN                                          370947        217
INDEPENDENT                                    210778          1
AMERICAN SOLIDARITY PARTY                       60982         87
AMERICAN INDEPENDENT                            60160      60160
PEACE & FREEDOM                                 51037      51037
CONSTITUTION PARTY                              45944         18
PARTY FOR SOCIALISM AND LIBERATION              31255         14
ALLIANCE                                        19334         13
GREEN-RAINBOW                                   18658      18658
THE BIRTHDAY PARTY                              15535        411
PACIFIC GREEN                                   11831      11831
US TAXPAYERS PARTY                               7235       7235
UNITY PARTY                                      6647        662
BREAD AND ROSES                                  5949         65
PROGRESSIVE PARTY                                5367        379
SOCIALIST WORKERS PARTY                          4020        354
INDEPENDENT AMERICAN PARTY                       3900        762
NATURAL LAW                                      2986       2986
BECOMING ONE NATION                              2702          6
DC STATEHOOD GREEN                               1726       1726
LIFE AND LIBERTY PARTY                           1372       1372
AMERICAN SHOPPING PARTY                          1183       1183
GRUMPY OLD PATRIOTS                              1175       1175
C.U.P                                            1125       1125
FREEDOM AND PROSPERITY                            749        749
LIFE , LIBERTY, CONSTITUTION                      668        668
PROHIBITION PARTY                                 577          9
GENEOLOGY KNOW YOUR FAMILY HISTORY PARTY          546        546
APPROVAL VOTING PARTY                             355        355
AMERICAN SOLIDARITY                               209        209
CONSTITUTION                                      208        208
SOCIALIST EQUALITY PARTY                          196        196
SOCIALIST WORKERS                                 195        195
LIBERTY UNION                                     166        166
BOILING FROG                                      141        141
PROHIBITION                                       137        137
BULL MOOSE                                        126        126
NON-AFFILIATED                                    117          1
UNAFFILIATED                                      100        100
APPROVAL VOTING                                    54         54

In [98]:
# Celkový počet odevzdaných hlasů pro kandidáty dvou hlavních stran (DEMOCRAT a REPUBLICAN) pro všechny volby od roku 1980.

data["year"] >=1980

filter=(data['party_detailed'].isin(['DEMOCRAT','REPUBLICAN'])) & (data['year']>=1980)

# filter

data[filter].groupby('year')['candidatevotes'].sum().sort_values(ascending=False)

year
2020    155485054
2008    128952681
2016    128369958
2012    124875967
2004    119322258
2000     99973686
1984     91616642
1988     90359319
1996     86299048
1992     83655660
1980     79123587
Name: candidatevotes, dtype: int64

In [99]:
# Celkový počet odevzdaných hlasů pro stát MONTANA pro všechny roky.

data_montana = data[data['state'] =='MONTANA']['candidatevotes'].sum()

data_montana

np.int64(5194180)

Pokračuj v práci se souborem votes.csv z předchozího cvičení. Ve volbách ve Spojených státech je důležité pořadí kandidáta/kandidátky v každém ze států, protože tento vítěz(ka) získá hlasy tzv. volitelů pro daný stát.

Pořadí na základě číselného sloupce je možné vypočítat pomocí metody rank(). Metoda rank() má parametr ascending, který určuje, jestli pořadí 1 dostane nejnižší nebo nejvyšší číslo. Pokud napíšeme rank(ascending=False), získá pořadí 1 nejvyšší hodnota ze sloupce, pořadí 2 druhá nejvyšší atd.

My ale chceme pořadí určit pro každý stát a rok samostatně, aby číslo 1 měl(a) vždy vítěz(ka) v daném státu a daném roce. Pokud bychom chtěli určit pořadí pro každý stát a rok samostatně, je možné využít metodu rank() v kombinaci s metodou groupby(). Jako "sloupec_poradi" zadáme sloupec, ze kterého chceme pořadí spočítat. Níže vidíš příklad, jak metodu použít.

data["jmeno_noveho_sloupce"] = data.groupby(["sloupec_1", "sloupec_2"])["sloupec_poradi"].rank()

Následně vytvoř tabulku, která bude obsahovat vítěznou stranu v jednotlivých státech ve volbách v roce 2020.

In [100]:
import pandas as pd
data["rank"] = data.groupby(["state", "year"])["candidatevotes"].rank(ascending=False)

In [101]:
data = pd.read_csv('votes.csv')

In [102]:
data["rank"] = data.groupby(["state", "year"])["candidatevotes"].rank(ascending=False)
data["rank"]

0       1.0
1       2.0
2       3.0
3       4.0
4       5.0
       ...
4282    3.0
4283    4.0
4284    5.0
4285    7.0
4286    6.0
Name: rank, Length: 4287, dtype: float64

In [119]:
winners_by_state_2020 = data[(data["rank"] == 1) & (data["year"] == 2020)][["state", "party_detailed"]]
winners_by_state_2020

                     state party_detailed
3741               ALABAMA     REPUBLICAN
3745                ALASKA     REPUBLICAN
3752               ARIZONA       DEMOCRAT
3771              ARKANSAS     REPUBLICAN
3773            CALIFORNIA       DEMOCRAT
3784              COLORADO       DEMOCRAT
3807           CONNECTICUT       DEMOCRAT
3838              DELAWARE       DEMOCRAT
3842  DISTRICT OF COLUMBIA       DEMOCRAT
3850               FLORIDA     REPUBLICAN
3878               GEORGIA       DEMOCRAT
3881                HAWAII       DEMOCRAT
3890                 IDAHO     REPUBLICAN
3904              ILLINOIS       DEMOCRAT
3925               INDIANA     REPUBLICAN
3938                  IOWA     REPUBLICAN
3950                KANSAS     REPUBLICAN
3953              KENTUCKY     REPUBLICAN
3970             LOUISIANA     REPUBLICAN
3981                 MAINE       DEMOCRAT
3989              MARYLAND       DEMOCRAT
4014         MASSACHUSETTS       DEMOCRAT
4020              MICHIGAN       DEMOCRAT
4032             MINNESOTA       DEMOCRAT
4042           MISSISSIPPI     REPUBLICAN
4050              MISSOURI     REPUBLICAN
4061               MONTANA     REPUBLICAN
4067              NEBRASKA     REPUBLICAN
4073                NEVADA       DEMOCRAT
4078         NEW HAMPSHIRE       DEMOCRAT
4100            NEW JERSEY       DEMOCRAT
4109            NEW MEXICO       DEMOCRAT
4113              NEW YORK       DEMOCRAT
4137        NORTH CAROLINA     REPUBLICAN
4144          NORTH DAKOTA     REPUBLICAN
4148                  OHIO     REPUBLICAN
4158              OKLAHOMA     REPUBLICAN
4165                OREGON       DEMOCRAT
4171          PENNSYLVANIA       DEMOCRAT
4173          RHODE ISLAND       DEMOCRAT
4181        SOUTH CAROLINA     REPUBLICAN
4185          SOUTH DAKOTA     REPUBLICAN
4188             TENNESSEE     REPUBLICAN
4201                 TEXAS     REPUBLICAN
4222                  UTAH     REPUBLICAN
4228               VERMONT       DEMOCRAT
4252              VIRGINIA       DEMOCRAT
4256            WASHINGTON       DEMOCRAT
4264         WEST VIRGINIA     REPUBLICAN
4267             WISCONSIN       DEMOCRAT
4281               WYOMING     REPUBLICAN

In [104]:
# Datum a čas a metoda shift

import pandas as pd

In [105]:
signal_monitoring = pd.read_csv("signal_monitoring.csv")
signal_monitoring

         event_type      event_date_time
0       signal lost  2021-02-03 00:40:08
1   signal restored  2021-02-03 01:14:11
2       signal lost  2021-02-05 19:14:19
3   signal restored  2021-02-05 19:46:29
4       signal lost  2021-02-06 14:31:34
5   signal restored  2021-02-06 14:48:24
6       signal lost  2021-02-08 04:59:20
7   signal restored  2021-02-08 05:38:29
8       signal lost  2021-02-09 14:21:25
9   signal restored  2021-02-09 14:42:22
10      signal lost  2021-02-09 20:07:49
11  signal restored  2021-02-09 20:31:30
12      signal lost  2021-02-12 03:49:42
13  signal restored  2021-02-12 04:26:48
14      signal lost  2021-02-12 16:53:17
15  signal restored  2021-02-12 17:18:18
16      signal lost  2021-02-13 21:15:48
17  signal restored  2021-02-13 21:31:22
18      signal lost  2021-02-15 07:19:44
19  signal restored  2021-02-15 08:10:17
20      signal lost  2021-02-16 09:24:59
21  signal restored  2021-02-16 09:38:25
22      signal lost  2021-02-18 01:48:55
23  signal restored  2021-02-18 02:36:30
24      signal lost  2021-02-19 21:36:04
25  signal restored  2021-02-19 21:48:37
26      signal lost  2021-02-22 09:58:49
27  signal restored  2021-02-22 10:58:35

In [106]:
signal_monitoring.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_type       28 non-null     str
 1   event_date_time  28 non-null     str
dtypes: str(2)
memory usage: 580.0 bytes

In [107]:
# pd.to_datetime(signal_monitoring["event_date_time"])
signal_monitoring["event_date_time"] = pd.to_datetime(signal_monitoring["event_date_time"])
signal_monitoring.info()

<class 'pandas.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_type       28 non-null     str
 1   event_date_time  28 non-null     datetime64[us]
dtypes: datetime64[us](1), str(1)
memory usage: 580.0 bytes

In [108]:
signal_monitoring["event_date"] = signal_monitoring["event_date_time"].dt.date
signal_monitoring.head()

        event_type     event_date_time  event_date
0      signal lost 2021-02-03 00:40:08  2021-02-03
1  signal restored 2021-02-03 01:14:11  2021-02-03
2      signal lost 2021-02-05 19:14:19  2021-02-05
3  signal restored 2021-02-05 19:46:29  2021-02-05
4      signal lost 2021-02-06 14:31:34  2021-02-06

In [109]:
signal_monitoring["event_end_date_time"] = signal_monitoring["event_date_time"].shift(periods=-1)
signal_monitoring.head()
#NaT - not a time

        event_type     event_date_time  event_date event_end_date_time
0      signal lost 2021-02-03 00:40:08  2021-02-03 2021-02-03 01:14:11
1  signal restored 2021-02-03 01:14:11  2021-02-03 2021-02-05 19:14:19
2      signal lost 2021-02-05 19:14:19  2021-02-05 2021-02-05 19:46:29
3  signal restored 2021-02-05 19:46:29  2021-02-05 2021-02-06 14:31:34
4      signal lost 2021-02-06 14:31:34  2021-02-06 2021-02-06 14:48:24

In [110]:
log = signal_monitoring[signal_monitoring["event_type"] == "signal lost"]

In [111]:
log["outage_length"] = log["event_end_date_time"] - log["event_date_time"]
log

,event_type,event_date_time,event_date,event_end_date_time,outage_length
0,signal lost,2021-02-03 00:40:08,2021-02-03,2021-02-03 01:14:11,0 days 00:34:03
2,signal lost,2021-02-05 19:14:19,2021-02-05,2021-02-05 19:46:29,0 days 00:32:10
4,signal lost,2021-02-06 14:31:34,2021-02-06,2021-02-06 14:48:24,0 days 00:16:50
6,signal lost,2021-02-08 04:59:20,2021-02-08,2021-02-08 05:38:29,0 days 00:39:09
8,signal lost,2021-02-09 14:21:25,2021-02-09,2021-02-09 14:42:22,0 days 00:20:57
10,signal lost,2021-02-09 20:07:49,2021-02-09,2021-02-09 20:31:30,0 days 00:23:41
12,signal lost,2021-02-12 03:49:42,2021-02-12,2021-02-12 04:26:48,0 days 00:37:06
14,signal lost,2021-02-12 16:53:17,2021-02-12,2021-02-12 17:18:18,0 days 00:25:01
16,signal lost,2021-02-13 21:15:48,2021-02-13,2021-02-13 21:31:22,0 days 00:15:34
18,signal lost,2021-02-15 07:19:44,2021-02-15,2021-02-15 08:10:17,0 days 00:50:33
20,signal lost,2021-02-16 09:24:59,2021-02-16,2021-02-16 09:38:25,0 days 00:13:26
22,signal lost,2021-02-18 01:48:55,2021-02-18,2021-02-18 02:36:30,0 days 00:47:35
24,signal lost,2021-02-19 21:36:04,2021-02-19,2021-02-19 21:48:37,0 days 00:12:33
26,signal lost,2021-02-22 09:58:49,2021-02-22,2021-02-22 10:58:35,0 days 00:59:46

In [112]:
log["event_date"].value_counts()

event_date
2021-02-09    2
2021-02-12    2
2021-02-03    1
2021-02-05    1
2021-02-06    1
2021-02-08    1
2021-02-13    1
2021-02-15    1
2021-02-16    1
2021-02-18    1
2021-02-19    1
2021-02-22    1
Name: count, dtype: int64

In [113]:
log.groupby("event_date").agg(outage_sum=("outage_length", "sum"))

                outage_sum
event_date
2021-02-03 0 days 00:34:03
2021-02-05 0 days 00:32:10
2021-02-06 0 days 00:16:50
2021-02-08 0 days 00:39:09
2021-02-09 0 days 00:44:38
2021-02-12 0 days 01:02:07
2021-02-13 0 days 00:15:34
2021-02-15 0 days 00:50:33
2021-02-16 0 days 00:13:26
2021-02-18 0 days 00:47:35
2021-02-19 0 days 00:12:33
2021-02-22 0 days 00:59:46

In [114]:
# seskupení kodu

log = signal_monitoring[signal_monitoring["event_type"] == "signal lost"]

log["outage_length"] = log["event_end_date_time"] - log["event_date_time"]

log.groupby("event_date").agg(outage_sum=("outage_length", "sum"))

                outage_sum
event_date
2021-02-03 0 days 00:34:03
2021-02-05 0 days 00:32:10
2021-02-06 0 days 00:16:50
2021-02-08 0 days 00:39:09
2021-02-09 0 days 00:44:38
2021-02-12 0 days 01:02:07
2021-02-13 0 days 00:15:34
2021-02-15 0 days 00:50:33
2021-02-16 0 days 00:13:26
2021-02-18 0 days 00:47:35
2021-02-19 0 days 00:12:33
2021-02-22 0 days 00:59:46

- CVIČENÍ Půlmaraton

In [115]:
import pandas as pd

In [116]:
df = pd.read_csv("half_marathon.csv")

df

              Jmeno  Rocnik       Cas  Rok zavodu
0    Aster Vladimír    1965  01:53:25        2019
1    Aster Vladimír    1965  02:00:19        2020
2     Asterová Jana    1974  02:16:59        2019
3     Asterová Jana    1974  02:30:01        2020
4     Baborová Anna    1990  01:58:20        2019
..              ...     ...       ...         ...
183    Švelch Rosťa    1966  01:55:11        2020
184    Žitková Jana    1974  02:45:54        2019
185    Žitková Jana    1974  02:42:48        2020
186   Žákovec Pavel    1966  02:03:36        2019
187   Žákovec Pavel    1966  02:07:37        2020

[188 rows x 4 columns]

In [117]:
df["Cas"]= pd.to_datetime(df["Cas"])

df

C:\Users\Kristynka\AppData\Local\Temp\ipykernel_25844\570386455.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Cas"]= pd.to_datetime(df["Cas"])

              Jmeno  Rocnik                 Cas  Rok zavodu
0    Aster Vladimír    1965 2026-04-28 01:53:25        2019
1    Aster Vladimír    1965 2026-04-28 02:00:19        2020
2     Asterová Jana    1974 2026-04-28 02:16:59        2019
3     Asterová Jana    1974 2026-04-28 02:30:01        2020
4     Baborová Anna    1990 2026-04-28 01:58:20        2019
..              ...     ...                 ...         ...
183    Švelch Rosťa    1966 2026-04-28 01:55:11        2020
184    Žitková Jana    1974 2026-04-28 02:45:54        2019
185    Žitková Jana    1974 2026-04-28 02:42:48        2020
186   Žákovec Pavel    1966 2026-04-28 02:03:36        2019
187   Žákovec Pavel    1966 2026-04-28 02:07:37        2020

[188 rows x 4 columns]

In [118]:
df["2019_Cas"] = df["Cas"].shift(1)

df = df[df["Rok_zavodu"]] == 2020

df

KeyError: 'Rok_zavodu'

In [ ]:
"]